### ISSUE TITLE
Minimal Bag of Visual Words Image Classifier

### ISSUE THREAD

**Issue by liboyin** [liboyin/horc#3]
https://github.com/shackenberg/Minimal-Bag-of-Visual-Words-Image-Classifier
Sakda is reviewing it.

**Comment by sakda-mail** [comment]
Refer to http://cs.brown.edu/courses/cs143/proj3/, it states the BoW accuracy is about 50-70%.
After test the code from Shackenburg, its result is about 80%.
Another version of code was created on Matlab, it also predicted about 80% correctly.
